services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  TYPO3\CMS\Impexp\:
    resource: '../Classes/*'

  TYPO3\CMS\Impexp\Utility\ImportExportUtility:
    public: true
