services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  TYPO3\CMS\Impexp\:
    resource: '../Classes/*'

  TYPO3\CMS\Impexp\Utility\ImportExportUtility:
    public: true

  TYPO3\CMS\Impexp\Command\ImportCommand:
    tags:
      - name: 'console.command'
        command: 'impexp:import'

  # Listener for old Signal Slots
  TYPO3\CMS\Impexp\Compatibility\SlotReplacement:
    tags:
      - name: event.listener
        identifier: 'legacy-slot'
        method: 'emitAfterImportExportInitialisationSignal'
        event: TYPO3\CMS\Impexp\Event\BeforeImportEvent
